### ISSUE TITLE
Dumper doesn't work on custom port

### ISSUE THREAD

**Issue by Vildis** [marcodsl/FiveM-Client-Dumper#5]
As the title says, the port is custom and here's the message that the dumper gives.

C:\Users\Vildis\Desktop>java -jar dump.jar -a 145.239.205.113 -p 30460
[2020-06-14 01:49:10,727] [34m[INFO][0;39m No ktor.deployment.watch patterns specified, automatic reload is not active
[2020-06-14 01:49:10,783] [34m[INFO][0;39m Responding at http://0.0.0.0:40120
[2020-06-14 01:49:11,039] [34m[INFO][0;39m Fetching manifest files...
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.gitlab.marcodsl.Resource.fetchManifest(Resource.kt:30)
        at com.gitlab.marcodsl.Application.<init>(Application.kt:40)
        at com.gitlab.marcodsl.Main.main(Main.kt:31)
Caused by: java.util.NoSuchElementException: Collection is empty.
        at kotlin.collections.CollectionsKt___CollectionsKt.random(_Collections.kt:500)
        at com.gitlab.marcodsl.cdp.CEFClient.<clinit>(CEFClient.kt:14)
        ... 3 more

**Comment by marcodsl** [comment]
https://github.com/marcodsl/FiveM-Client-Dumper/commit/261d538d894b10c2cf47715961f7188e20687fbf
